Repository I-Taxi/itaxi-front, pull requests merged in 2023-02, with the labels that each got.

#119 refactor[#117] : main screen 조회 및 모집 화면 합치기
  lib/controller/screenController.dart
  lib/gatherScreen.dart
  lib/home.dart
  lib/mainScreen.dart
  lib/placeSearch/placeSearchController.dart
  lib/src/theme.dart
  lib/stopoverScreen.dart
  lib/widget/setDepDstWidget.dart
Labels: refactor

#135 feat[#133]: 타임라인 리스트 UI 최신버전화
  assets/icon/car_gray.png
  assets/icon/ktx_gray.png
  lib/timeline/historyListContainer.dart
  lib/timeline/specificInformation.dart
  lib/timeline/timelineScreen.dart
  lib/timeline/timelineSoonInfoCard.dart
  pubspec.yaml
Labels: feat

#142 feat[#134] : 경유지 기능 추가
  assets/place/dep-stop-dest.png
  assets/subtract_place.png
  lib/controller/placeController.dart
  lib/mainScreen.dart
  lib/model/post.dart
  lib/placeSearch/placeSearchController.dart
  lib/placeSearch/searchScreen.dart
  lib/widget/mainScreenSettingWidget.dart
  pubspec.yaml
Labels: feat

#143 feat[#134] : 경유지 글자색 변경
  lib/widget/mainScreenSettingWidget.dart
Labels: feat

#155 hotfix[#154]: fix changed widget name
  lib/chat/newChatroomScreen.dart
  lib/widget/chatroomListListTile.dart
Labels: fix

#158 fix/#157 main screen 피드백 적용
  lib/controller/addKtxPostController.dart
  lib/controller/ktxPlaceController.dart
  lib/controller/screenController.dart
  lib/ktxScreen.dart
  lib/mainScreen.dart
  lib/placeSearch/ktxPlaceSearchController.dart
  lib/placeSearch/ktxPlaceSearchWidget.dart
  lib/placeSearch/ktxSearchScreen.dart
  lib/widget/ktxScreenSettingWidget.dart
  lib/widget/mainScreenSettingWidget.dart
Labels: fix

#168 feat[#154]: 타임라인 경유지 추가
  lib/controller/historyController.dart
  lib/model/post.dart
  lib/timeline/timelineDetailScreen.dart
  lib/timeline/timelineScreen.dart
  lib/timeline/timelineSoonInfoCard.dart
Labels: feat

#174 refactor[#173]: member bank 관련 정보 삭제
  lib/controller/signUpController.dart
  lib/controller/userController.dart
  lib/model/user.dart
  lib/model/userInfoList.dart
  lib/settings/userInfoRefactorScreen.dart
Labels: refactor

#177 fix[#171] : history contoller 리팩토링
  lib/chat/chatRoomListScreen.dart
  lib/controller/historyController.dart
  lib/controller/postController.dart
  lib/model/history.dart
  lib/settings/settingScreen.dart
  lib/timeline/historyListContainer.dart
  lib/timeline/timelineScreen.dart
  lib/timeline/timelineSoonInfoCard.dart
  lib/widget/chatroomListListTile.dart
  lib/widget/postTypeToString.dart
Labels: fix

#180 fix[#163] : ktx 채팅방 개선
  lib/chat/chatRoomScreen.dart
  lib/chat/newChatroomScreen.dart
  lib/controller/addKtxPostController.dart
  lib/controller/addPostController.dart
  lib/controller/chatRoomController.dart
  lib/controller/ktxPostController.dart
  lib/controller/screenController.dart
  lib/model/history.dart
  lib/model/ktxPost.dart
  lib/repository/ktxChatRepository.dart
  lib/timeline/timelineDetailScreen.dart
  lib/timeline/timelineSoonInfoCard.dart
  lib/widget/chatroomListListTile.dart
  lib/widget/ktxScreenSettingWidget.dart
  lib/widget/timelineDialog.dart
Labels: fix

#182 fix[#181] : mainscreen ktx timepicker 개선
  lib/chat/newChatroomScreen.dart
  lib/widget/ktxScreenSettingWidget.dart
  lib/widget/mainScreenSettingWidget.dart
  lib/widget/setTimeDateFormater.dart
Labels: fix

#190 feat[#175] : timeline screen 상호작용 추가
  lib/controller/screenController.dart
  lib/signInUp/signInScreen.dart
  lib/timeline/historyListContainer.dart
  lib/timeline/passengerListTile.dart
  lib/timeline/timelineDetailScreen.dart
  lib/timeline/timelineScreen.dart
  lib/timeline/timelineSoonInfoCard.dart
  lib/widget/ktxScreenSettingWidget.dart
Labels: feat

#194 fix[#193] : fix main screen null error
  lib/mainScreen.dart
Labels: fix

#195 fix[#193] : 채팅방 error 수정
  lib/chat/newChatroomScreen.dart
  lib/controller/historyController.dart
Labels: fix

#197 fix[#196] : post controller joiner 수정
  lib/controller/ktxPostController.dart
  lib/controller/postController.dart
  lib/controller/userController.dart
  lib/mainScreen.dart
  lib/widget/postListTile.dart
Labels: fix

#198 fix[#189] : 채팅방 아무것도 없을 때 UI 수정
  lib/chat/chatDetailListTile.dart
  lib/chat/chatRoomListScreen.dart
  lib/chat/chatRoomScreen_bak.dart
  lib/chat/chatroomDetailScreen.dart
  lib/controller/signInController.dart
  lib/main.dart
  lib/model/post.dart
  lib/signInUp/signInScreen.dart
  lib/signInUp/splashScreen.dart
  lib/timeline/timelineSoonInfoCard.dart
  lib/widget/addPostDialog.dart
  lib/widget/chatroomListListTile.dart
  lib/widget/ktxPostListTile.dart
  lib/widget/postListTile.dart
  lib/widget/timelineDialog.dart
Labels: fix

#199 fix[#189] : 채팅방 에러 화면 추가
  lib/chat/chatRoomListScreen.dart
  lib/chat/chatroomDetailScreen.dart
  lib/controller/chatRoomController.dart
  lib/controller/postController.dart
  lib/controller/signInController.dart
  lib/main.dart
  lib/model/history.dart
  lib/widget/chatroomListListTile.dart
  lib/widget/mainScreenSettingWidget.dart
  lib/widget/showErrorDialog.dart
Labels: fix

#207 fix[#206] : 네비게이션 바 UI 수정
  lib/controller/navigationController.dart
  lib/home.dart
  lib/mainScreen.dart
  lib/src/theme.dart
Labels: fix

#214 fix[#208] : search screen ui 수정
  assets/icon/add.png
  assets/icon/trash_can.png
  lib/controller/placeController.dart
  lib/placeSearch/placeSearchController.dart
  lib/placeSearch/placeSearchWidget.dart
  lib/placeSearch/searchScreen.dart
  lib/src/theme.dart
  pubspec.yaml
Labels: fix

#221 fix[#215] : check screen 수정
  lib/controller/screenController.dart
  lib/mainScreen.dart
  lib/placeSearch/placeSearchWidget.dart
  lib/timeline/checkPlaceScreen.dart
  lib/widget/mainScreenSettingWidget.dart
  lib/widget/postListTile.dart
Labels: fix

#243 fix[#240]: fix overflow, make text center
  lib/controller/ktxPlaceController.dart
  lib/placeSearch/ktxSearchScreen.dart
  lib/placeSearch/placeSearchScreen.dart
  lib/timeline/timelineScreen.dart
Labels: fix
